fix: add checks for sanitizing user input

diff --git a/git-credential-gpgcreds b/git-credential-gpgcreds
--- a/git-credential-gpgcreds
+++ b/git-credential-gpgcreds
@@ -1,6 +1,7 @@
 #!/usr/bin/env bash
 # gpgcreds
 # A git credential helper to store git credentials encrypted on disk
+set -euo pipefail
 
 HELP_MSG=$(cat <<-E_HELP_MSG
     USAGE: gpgcreds
@@ -94,7 +95,7 @@ read_params_dumb() {
 check_creds() {
     local -n __creds=$1;
     [[ \
-        ( -n "${__creds[url]}" || (-n "${__creds[protocol]}" && -n "${__creds[host]}" ) ) \
+        ( (-n "${__creds[protocol]}" && -n "${__creds[host]}" ) || -n "${__creds[url]}" ) \
         && -n "${__creds[username]}" \
         && -n "${__creds[password]}" \
     ]];
@@ -108,10 +109,10 @@ format_creds() {
     local -n _creds=$1;
     local -n _fmt_creds=$2;
     if check_creds _creds; then
-        if [[ -n "${_creds[url]}" ]]; then
-            _fmt_creds="${_creds[url]/:\/\//:\/\/${_creds[username]}:${_creds[password]}@}";
-        elif [[ -n "${_creds[protocol]}" && -n "${_creds[host]}" ]]; then
+        if [[ -n "${_creds[protocol]}" && -n "${_creds[host]}" ]]; then
             _fmt_creds="${_creds[protocol]}://${_creds[username]}:${_creds[password]}@${_creds[host]}";
+        elif [[ -n "${_creds[url]}" ]]; then
+            _fmt_creds="${_creds[url]/:\/\//:\/\/${_creds[username]}:${_creds[password]}@}";
         fi
     else
         echo "(E): Missing required git credentials attributes. See '-h' for usage." >&2;
@@ -150,6 +151,9 @@ if [[ -n "$STORE_PREFIX" ]]; then
 else
     GPGCREDS_STORE="$DEFAULT_CREDS_DIR/${DEFAULT_PREFIX}.gpgcreds.cyp";
 fi
+if [[ ! "${STORE_PREFIX}" =~ ^[a-zA-Z0-9_-]+$ ]]; then
+    echo "(E): Invalid namespace. See '-h' for usage." >&2;
+fi
 
 declare -A git_creds;
 declare fmt_creds;
@@ -167,15 +171,23 @@ case "$1" in
             echo "(E): Missing git config user.signingkey.";
             exit 22;
         fi
-        gpg --recipient "$gpg_key" -e > "${GPGCREDS_STORE}" < <(printf "%s\n" "${fmt_creds}");
+        if ! gpg --list-keys "${gpg_key}" &>/dev/null; then
+            echo "(E): GPG Key '${gpg_key}' not found in keyring." >&2;
+            exit 1;
+        fi
+        # gpg --recipient "${gpg_key}" -e > "${GPGCREDS_STORE}" < <(printf "%s\n" "${fmt_creds}");
+        gpg --recipient "${gpg_key}" -e > "${GPGCREDS_STORE}" <<< "${fmt_creds}";
         exit 0;
     ;;
     get | fill)
         echo 'quit=true'
-        URL_RE='^([a-zA-Z]+)://(.*)';
+        URL_RE='^([a-zA-Z0-9+.-]+)://(.*)';
         read_params git_creds;
         declare -A search_creds;
-        if [[ -n "${git_creds[url]}" ]]; then
+        if [[ -n "${git_creds[protocol]}" && -n "${git_creds[host]}" ]]; then
+            search_creds[protocol]=${git_creds[protocol]}
+            search_creds[host]=${git_creds[host]}
+        elif [[ -n "${git_creds[url]}" ]]; then
             if [[ "${git_creds[url]}" =~ $URL_RE ]]; then
                 search_creds[protocol]="${BASH_REMATCH[1]}"
                 search_creds[host]="${BASH_REMATCH[2]}"
@@ -183,21 +195,30 @@ case "$1" in
                 echo "(E): Malformed url."
                 exit 22;
             fi
-        elif [[ -n "${git_creds[protocol]}" && -n "${git_creds[host]}" ]]; then
-            search_creds[protocol]=${git_creds[protocol]}
-            search_creds[host]=${git_creds[host]}
         else
             echo "(E): Missing required git credential attributes. See '-h' for usage." >&2;
+            exit 22;
+        fi
+
+        # Validate user input used in REGEX matches
+        if [[ ! "${search_creds[protocol]}" =~ ^[a-zA-Z][a-zA-Z0-9+.-]*$ ]]; then
+            echo "(E): Invalid URI protocol format." >&2;
+            exit 22;
+        fi
+        # Check for valid hostnames, which may include '.'
+        if [[ ! "${search_creds[host]}" =~ ^[a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?(\.[a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?)*$ ]]; then
+            echo "(E): Invalid URI protocol format." >&2;
             exit 22;
         fi
 
         declare -A match_creds;
         gpg_grep_rc=1
         while read -r line; do
-            if [[ "${line}" =~ ^${search_creds[protocol]}://(([^:@]+)(:([^@]+))?@)?${search_creds[host]}$ ]]; then
+            # if [[ "${line}" =~ ^${search_creds[protocol]}://(([^:@]+)(:([^@]+))?@)?${search_creds[host]}$ ]]; then
+            if [[ "${line}" =~ ^${search_creds[protocol]}://([^:@]+):?(.*)@${search_creds[host]}$ ]]; then
                 gpg_grep_rc=$?;
-                match_creds[username]="${BASH_REMATCH[2]}";
-                match_creds[password]="${BASH_REMATCH[4]}";
+                match_creds[username]="${BASH_REMATCH[1]}";
+                match_creds[password]="${BASH_REMATCH[2]}";
                 # echo "${line}";
                 echo "quit=true";
                 echo "username=${match_creds[username]}"
