fix: update error message terminology to match git-credential docs

diff --git a/git-credential-gpgcreds b/git-credential-gpgcreds
--- a/git-credential-gpgcreds
+++ b/git-credential-gpgcreds
@@ -75,10 +75,10 @@ read_params() {
                 d_creds[password]="${attrs[1]}";
                 ;;
             path | "capability[]" | "wwwauth[]" | "state[]" | continue  | ephemeral | credential | authtype | oauth_refresh_token | password_expiry_utc)
-                echo "(W): Skipping unsupported keyword: '${attrs[0]}'." >&2;
+                echo "(W): Skipping unsupported git attribute: '${attrs[0]}'." >&2;
                 ;;
             *)
-                echo "Unrecognized input keyword '${attrs[0]}'." >&2;
+                echo "(E): Unrecognized git attribute '${attrs[0]}'." >&2;
                 exit 1;
         esac
     done
@@ -114,7 +114,7 @@ format_creds() {
             _fmt_creds="${_creds[protocol]}://${_creds[username]}:${_creds[password]}@${_creds[host]}";
         fi
     else
-        echo "(E): Missing required git credentials parameters. See '-h' for usage." >&2;
+        echo "(E): Missing required git credentials attributes. See '-h' for usage." >&2;
         exit 22;
     fi
 }
@@ -187,7 +187,7 @@ case "$1" in
             search_creds[protocol]=${git_creds[protocol]}
             search_creds[host]=${git_creds[host]}
         else
-            echo "(E): Missing required git credentials parameters. See '-h' for usage." >&2;
+            echo "(E): Missing required git credential attributes. See '-h' for usage." >&2;
             exit 22;
         fi
 
@@ -207,7 +207,7 @@ case "$1" in
         done < <(gpg -dq "${GPGCREDS_STORE}")
         gpg_grep_rc=$gpg_grep_rc || $?;
         if [[ $gpg_grep_rc -ne 0 ]]; then
-            echo "(E):  Unable to decrypt GPG credential store file with matching parameters." >&2;
+            echo "(E):  Unable to decrypt GPG credential store file with matching git attributes." >&2;
             exit $gpg_grep_rc;
         fi
         exit 0;
